### ISSUE TITLE
Add packages

### ISSUE THREAD

**Issue by bobbrodie** [rocketsofawesome/newgistics-ruby#38]
Newgistics returns an array of `<Packages>` similar to the array of `<Fees>`:
```xml
<Packages>
    <Package id="12345678">
        <TrackingNumber>9400100000000000000000</TrackingNumber>
        <Weight>1.00000</Weight>
        <BillableWeight>1.00000</BillableWeight>
        <Height>10.00000</Height>
        <Width>10.00000</Width>
        <Depth>5.50000</Depth>
        <Items>
            <Item id="1234567">
                <SKU>ABC123</SKU>
                <Qty>1</Qty>
            </Item>
        </Items>
    </Package>
</Packages>
```

Adding support for this would be super helpful. I can contribute this, but wanted to get in a placeholder.

**Comment by manmartinez** [comment]
This sounds great! If you want to submit a PR we'd be happy to take a look :)

**Comment by bobbrodie** [comment]
Pull request submitted, and we're using it on a report. So far we haven't run into any issues. Thanks!

**Comment by jrusso1020** [comment]
Going to close this since it was merged in a while back
